AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Stack template for creating networking resources for a project.

Mappings:
  CidrBlockMap:
    InternetBlockIpv4:
      "block": "0.0.0.0/0"
    InternetBlockIpv6:
      "block": "::/0"
    VpcBlock:
      "block": "10.0.0.0/16"
    PublicBlock1:
      "block": "10.0.0.0/24"
    PrivateBlock1:
      "block": "10.0.1.0/24"
    PublicBlock2:
      "block": "10.0.2.0/24"
    PrivateBlock2:
      "block": "10.0.3.0/24"

Parameters:
  ProjectNameParam:
    Type: String
    Description: Project name tag
    Default: "network"
  EnvParam:
    Type: String
    Description: Environment tag
    Default: "dev"
    AllowedValues:
      - "prod"
      - "dev"
      - "qa"
      - "test"
  ResourceRandom:
    Type: String
    Description: Random string for resources created in this stack

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [CidrBlockMap, VpcBlock, block]
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-vpc-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-igw-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  VpcInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: Vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !FindInMap [CidrBlockMap, PublicBlock1, block]
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-public1-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !FindInMap [CidrBlockMap, PrivateBlock1, block]
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-private1-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !FindInMap [CidrBlockMap, PublicBlock2, block]
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-public2-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !FindInMap [CidrBlockMap, PrivateBlock2, block]
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-private2-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  PublicRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-rtb-public-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: !Sub "${ProjectNameParam}-rtb-private-${ResourceRandom}-${EnvParam}"
        - Key: project
          Value: !Ref ProjectNameParam
        - Key: env
          Value: !Ref EnvParam

  PublicRouteInternetIpv4:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !FindInMap [CidrBlockMap, InternetBlockIpv4, block]
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
         Ref: PublicRouteTable1

  PublicRouteInternetIpv6:
    Type: AWS::EC2::Route
    Properties:
      DestinationIpv6CidrBlock: !FindInMap [CidrBlockMap, InternetBlockIpv6, block]
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
         Ref: PublicRouteTable1

  Public1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable1
      SubnetId:
        Ref: PublicSubnet1

  Public2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable1
      SubnetId:
        Ref: PublicSubnet2

  Private1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable1
      SubnetId:
        Ref: PrivateSubnet1

  Private2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable1
      SubnetId:
        Ref: PrivateSubnet2

Outputs:
  Vpc:
    Description: Id of the VPC created in this stack
    Value: !Ref Vpc
  PublicSubnet1Id:
    Description: Id of the 1st public subnet created in this stack
    Value: !Ref PublicSubnet1
  PublicSubnet1Az:
    Description: Az of the 1st public subnet created in this stack
    Value: !GetAtt [PublicSubnet1, AvailabilityZone]
  PrivateSubnet1Id:
    Description: Id of the 1st private subnet created in this stack
    Value: !Ref PrivateSubnet1
  PrivateSubnet1Az:
    Description: Az of the 1st private subnet created in this stack
    Value: !GetAtt [PrivateSubnet1, AvailabilityZone]
